![](https://velog.velcdn.com/images/hyejinbeck/post/9d60c960-912d-48e9-b375-6331e8913065/image.png)


![](https://velog.velcdn.com/images/hyejinbeck/post/f3b13344-c1eb-4ea3-9826-78a7d3052a20/image.png)

![](https://velog.velcdn.com/images/hyejinbeck/post/23f0c90b-9fb3-44ea-ba49-766898f3a821/image.png)

In [111]:
# 설치 파일
!pip freeze > requirements.txt

In [112]:
# 필요함수
import pandas as pd 

In [113]:
# 불러오기
data = pd.read_csv('./Dataset/Dataset_02.csv')
data.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [114]:
# 데이터 확인 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


# 부합조건 찾기

In [115]:
# 컬럼확인
data.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')

In [116]:
# 환자 조건1 : 여자
data['Sex'].unique()

array(['F', 'M'], dtype=object)

In [117]:
# 환자 조건2 : 혈압 High
data['BP'].unique()

array(['HIGH', 'LOW', 'NORMAL'], dtype=object)

In [118]:
# 환자 조건3 : 콜레스테롤 Normal
data['Cholesterol'].unique()

array(['HIGH', 'NORMAL'], dtype=object)

In [119]:
# 조건(성별,콜레스테롤) 걸어서 확인
pd.crosstab(
    index=[data.Sex],              # 성별
    columns = data.Cholesterol     # 콜레스테롤
)

Cholesterol  HIGH  NORMAL
Sex                      
F              49      47
M              54      50

In [120]:
# 조건(성별+혈압,콜레스테롤) 걸어서 확인
pd.crosstab(
    index=[data.Sex,  data.BP],   # 성별 + 혈압
    columns = data.Cholesterol,   # 콜레스테롤 
)

Cholesterol  HIGH  NORMAL
Sex BP                   
F   HIGH       17      21
    LOW        14      14
    NORMAL     18      12
M   HIGH       18      21
    LOW        17      19
    NORMAL     19      10

In [121]:
# 조건(성별+혈압,콜레스테롤)의 각 비율(빈도)
pd.crosstab(
    index=[data.Sex,  data.BP],   # 성별 + 혈압
    columns = data.Cholesterol,   # 콜레스테롤 
    normalize=True,
)

Cholesterol   HIGH  NORMAL
Sex BP                    
F   HIGH     0.085   0.105
    LOW      0.070   0.070
    NORMAL   0.090   0.060
M   HIGH     0.090   0.105
    LOW      0.085   0.095
    NORMAL   0.095   0.050

In [122]:
# 조건 부합되는 특정값 추출 
q1=\
pd.crosstab(
    index=[data.Sex,  data.BP],   # 성별 + 혈압
    columns = data.Cholesterol,   # 콜레스테롤 
    normalize=True,
)

q1.loc[('F', 'HIGH'), 'NORMAL']

0.105

#  변수생성(수치형->범주형)

In [123]:
# 기존데이터 복사
q2 = data.copy()

In [124]:
q2.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [125]:
# 나이 Age (수치형) 컬럼 확인
q2['Age'].describe()

count    200.000000
mean      44.315000
std       16.544315
min       15.000000
25%       31.000000
50%       45.000000
75%       58.000000
max       74.000000
Name: Age, dtype: float64

In [126]:
# 칼륨대비나트륨비율 Na_to_K (수치형) 컬럼 확인
q2['Na_to_K'].describe()

count    200.000000
mean      16.084485
std        7.223956
min        6.269000
25%       10.445500
50%       13.936500
75%       19.380000
max       38.247000
Name: Na_to_K, dtype: float64

In [127]:
# 컬럼생성np위한 함수
import numpy as np

In [128]:
# 나이 Age 관련 컬럼 생성 (수치형 --> 범주형 )

q2['Age_gr'] = np.where(q2.Age < 20 , 10 ,           # Age가 20미만이면 10, 아니면 
                        np.where(q2.Age < 30 , 20 , 
                                 np.where(q2.Age < 40 , 30 , 
                                          np.where(q2.Age < 50 , 40 ,
                                                   np.where(q2.Age < 60 , 50 , 
                                                            60   )))))
q2

Age Sex      BP Cholesterol  Na_to_K   Drug  Age_gr
0     23   F    HIGH        HIGH   25.355  DrugY      20
1     47   M     LOW        HIGH   13.093  drugC      40
2     47   M     LOW        HIGH   10.114  drugC      40
3     28   F  NORMAL        HIGH    7.798  drugX      20
4     61   F     LOW        HIGH   18.043  DrugY      60
..   ...  ..     ...         ...      ...    ...     ...
195   56   F     LOW        HIGH   11.567  drugC      50
196   16   M     LOW        HIGH   12.006  drugC      10
197   52   M  NORMAL        HIGH    9.894  drugX      50
198   23   M  NORMAL      NORMAL   14.020  drugX      20
199   40   F     LOW      NORMAL   11.349  drugX      40

[200 rows x 7 columns]

In [129]:
# 칼륨대비나트륨비율 Na_to_K 관련 컬럼 생성 (수치형 --> 범주형 )

q2['Na_K_gr'] = np.where(q2.Na_to_K <= 10 , 'Lv1',           # Na_to_k가 10이하면 'Lv1'로 
                        np.where(q2.Na_to_K <= 20 , 'Lv2', 
                                 np.where(q2.Na_to_K <= 30 , 'Lv3',
                                          'Lv4' )))
q2

Age Sex      BP Cholesterol  Na_to_K   Drug  Age_gr Na_K_gr
0     23   F    HIGH        HIGH   25.355  DrugY      20     Lv3
1     47   M     LOW        HIGH   13.093  drugC      40     Lv2
2     47   M     LOW        HIGH   10.114  drugC      40     Lv2
3     28   F  NORMAL        HIGH    7.798  drugX      20     Lv1
4     61   F     LOW        HIGH   18.043  DrugY      60     Lv2
..   ...  ..     ...         ...      ...    ...     ...     ...
195   56   F     LOW        HIGH   11.567  drugC      50     Lv2
196   16   M     LOW        HIGH   12.006  drugC      10     Lv2
197   52   M  NORMAL        HIGH    9.894  drugX      50     Lv1
198   23   M  NORMAL      NORMAL   14.020  drugX      20     Lv2
199   40   F     LOW      NORMAL   11.349  drugX      40     Lv2

[200 rows x 8 columns]

# 독립성 검정 (샘플용으로 하나만)

```
문자형String 타입의 독립성 검정 == 카이스퀘어
```

In [130]:
# 카이스퀘어 환경 다운받기 
# !pip install scipy
!pip install --upgrade pip

In [131]:
# 카이스퀘어 함수
from scipy.stats import chi2_contingency

In [132]:
# x변수(Sex기준)으로 y변수(Drug)와의 빈도표
tab = pd.crosstab(index=q2['Sex'],columns=q2['Drug'])
tab

Drug  DrugY  drugA  drugB  drugC  drugX
Sex                                    
F        47      9      6      7     27
M        44     14     10      9     27

In [133]:
# x변수(Sex기준)으로 y변수(Drug)와의 빈도표로 카이스퀘어 검정 진행 

chi2_contingency(tab)

# 결과 
# 카이스퀘어 통계량 statistic 
# pvalue 
# 자유도 dof 
# 기대빈도 expected_freq (array형태) 

Chi2ContingencyResult(statistic=2.119248418109203, pvalue=0.7138369773987128, dof=4, expected_freq=array([[43.68, 11.04,  7.68,  7.68, 25.92],
       [47.32, 11.96,  8.32,  8.32, 28.08]]))

# 독립성 검정 (x변수들 반복문=자동화)¶

In [134]:
# 변수 확인
q2.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug', 'Age_gr',
       'Na_K_gr'],
      dtype='object')

In [135]:
# 필요 변수 x 
features = ['Sex','BP','Cholesterol','Age_gr','Na_K_gr']

In [136]:
# 검정진행 & pvalue값들만 담을 변수
answer = []

# 변수별 검정 진행 (반복문) + p-value만 추출 
for i in features : 
    tab = pd.crosstab(index=q2[i],columns=q2['Drug'])
    pvalue = chi2_contingency(tab)
    answer.append([i,pvalue])

answer

[['Sex',
  Chi2ContingencyResult(statistic=2.119248418109203, pvalue=0.7138369773987128, dof=4, expected_freq=array([[43.68, 11.04,  7.68,  7.68, 25.92],
         [47.32, 11.96,  8.32,  8.32, 28.08]]))],
 ['BP',
  Chi2ContingencyResult(statistic=143.2328718496999, pvalue=5.0417334144665895e-27, dof=8, expected_freq=array([[35.035,  8.855,  6.16 ,  6.16 , 20.79 ],
         [29.12 ,  7.36 ,  5.12 ,  5.12 , 17.28 ],
         [26.845,  6.785,  4.72 ,  4.72 , 15.93 ]]))],
 ['Cholesterol',
  Chi2ContingencyResult(statistic=19.609657681313475, pvalue=0.0005962588389856497, dof=4, expected_freq=array([[46.865, 11.845,  8.24 ,  8.24 , 27.81 ],
         [44.135, 11.155,  7.76 ,  7.76 , 26.19 ]]))],
 ['Age_gr',
  Chi2ContingencyResult(statistic=46.440652324723914, pvalue=0.0007010113024729462, dof=20, expected_freq=array([[ 5.46 ,  1.38 ,  0.96 ,  0.96 ,  3.24 ],
         [15.925,  4.025,  2.8  ,  2.8  ,  9.45 ],
         [16.835,  4.255,  2.96 ,  2.96 ,  9.99 ],
         [17.29 ,  4.37 ,  3.04 ,

In [143]:
# 반복문속, 변수별 빈도만 확인
pd.crosstab(index=q2[i],columns=q2['Drug'])

Drug     DrugY  drugA  drugB  drugC  drugX
Na_K_gr                                   
Lv1          0      7      5      4     22
Lv2         44     16     11     12     32
Lv3         35      0      0      0      0
Lv4         12      0      0      0      0

In [138]:
# pvalue값 확인
chi2_contingency(tab)

Chi2ContingencyResult(statistic=93.31006327437028, pvalue=1.1254641594413981e-14, dof=12, expected_freq=array([[17.29 ,  4.37 ,  3.04 ,  3.04 , 10.26 ],
       [52.325, 13.225,  9.2  ,  9.2  , 31.05 ],
       [15.925,  4.025,  2.8  ,  2.8  ,  9.45 ],
       [ 5.46 ,  1.38 ,  0.96 ,  0.96 ,  3.24 ]]))

In [144]:
# 검정진행 & pvalue값들만 담을 변수
answer = []

# 변수별 빈도표 에서 각각의 검정진행한 통계량만 추출
for i in features : 
    tab = pd.crosstab(index=q2[i],columns=q2['Drug'])
    pvalue = chi2_contingency(tab)[0]    # [0]카이스퀘어 통계량
    answer.append([i,pvalue])

answer

[['Sex', 2.119248418109203],
 ['BP', 143.2328718496999],
 ['Cholesterol', 19.609657681313475],
 ['Age_gr', 46.440652324723914],
 ['Na_K_gr', 93.31006327437028]]

In [145]:
# 검정진행 & pvalue값들만 담을 변수
answer = []

# 변수별 빈도표 에서 각각의 pvalue인덱스만 추출
for i in features : 
    tab = pd.crosstab(index=q2[i],columns=q2['Drug'])
    pvalue = chi2_contingency(tab)[1]    # [1]pvalue인덱스만
    answer.append([i,pvalue])

answer

[['Sex', 0.7138369773987128],
 ['BP', 5.0417334144665895e-27],
 ['Cholesterol', 0.0005962588389856497],
 ['Age_gr', 0.0007010113024729462],
 ['Na_K_gr', 1.1254641594413981e-14]]

In [147]:
# 검정진행 & pvalue값들만 담을 변수
answer = []

# 변수별 빈도표 에서 각각의 자유도만 추출
for i in features : 
    tab = pd.crosstab(index=q2[i],columns=q2['Drug'])
    pvalue = chi2_contingency(tab)[2]    # [2]자유도 dof 
    answer.append([i,pvalue])

answer

[['Sex', 4], ['BP', 8], ['Cholesterol', 4], ['Age_gr', 20], ['Na_K_gr', 12]]

In [149]:
# 검정진행 & pvalue값들만 담을 변수
answer = []

# 변수별 빈도표 에서 각각의 기대빈도만 추출 
for i in features : 
    tab = pd.crosstab(index=q2[i],columns=q2['Drug'])
    pvalue = chi2_contingency(tab)[3]    # [3]기대빈도 expected_freq(array형태) 
    answer.append([i,pvalue])

answer

[['Sex',
  array([[43.68, 11.04,  7.68,  7.68, 25.92],
         [47.32, 11.96,  8.32,  8.32, 28.08]])],
 ['BP',
  array([[35.035,  8.855,  6.16 ,  6.16 , 20.79 ],
         [29.12 ,  7.36 ,  5.12 ,  5.12 , 17.28 ],
         [26.845,  6.785,  4.72 ,  4.72 , 15.93 ]])],
 ['Cholesterol',
  array([[46.865, 11.845,  8.24 ,  8.24 , 27.81 ],
         [44.135, 11.155,  7.76 ,  7.76 , 26.19 ]])],
 ['Age_gr',
  array([[ 5.46 ,  1.38 ,  0.96 ,  0.96 ,  3.24 ],
         [15.925,  4.025,  2.8  ,  2.8  ,  9.45 ],
         [16.835,  4.255,  2.96 ,  2.96 ,  9.99 ],
         [17.29 ,  4.37 ,  3.04 ,  3.04 , 10.26 ],
         [15.015,  3.795,  2.64 ,  2.64 ,  8.91 ],
         [20.475,  5.175,  3.6  ,  3.6  , 12.15 ]])],
 ['Na_K_gr',
  array([[17.29 ,  4.37 ,  3.04 ,  3.04 , 10.26 ],
         [52.325, 13.225,  9.2  ,  9.2  , 31.05 ],
         [15.925,  4.025,  2.8  ,  2.8  ,  9.45 ],
         [ 5.46 ,  1.38 ,  0.96 ,  0.96 ,  3.24 ]])]]

# p-value값 찾기

In [154]:
# 검정진행 & pvalue값들만 담을 변수
answer = []

# 변수별 빈도표 에서 각각의 pvalue인덱스만 추출
for i in features : 
    tab = pd.crosstab(index=q2[i],columns=q2['Drug'])
    pvalue = chi2_contingency(tab)[1]    # [1]pvalue인덱스만
    answer.append([i,pvalue])

answer

[['Sex', 0.7138369773987128],
 ['BP', 5.0417334144665895e-27],
 ['Cholesterol', 0.0005962588389856497],
 ['Age_gr', 0.0007010113024729462],
 ['Na_K_gr', 1.1254641594413981e-14]]

In [158]:
# 데이터프레임화
answer = pd.DataFrame(
    answer, 
    columns = ['features','pvalue']  # 부여할 컬럼 작명
)
answer

features        pvalue
0          Sex  7.138370e-01
1           BP  5.041733e-27
2  Cholesterol  5.962588e-04
3       Age_gr  7.010113e-04
4      Na_K_gr  1.125464e-14

In [171]:
# pvalue값이 유의수준보다 작으면 연관성이 있는 값
answer['pvalue']<0.05

0    False
1     True
2     True
3     True
4     True
Name: pvalue, dtype: bool

In [189]:
# 연관성 있는 값들만 데이터프레임화
answer[answer['pvalue']<0.05]     # Sex 제거됨

features        pvalue
1           BP  5.041733e-27
2  Cholesterol  5.962588e-04
3       Age_gr  7.010113e-04
4      Na_K_gr  1.125464e-14

In [190]:
# 데이터프레임 중에서 pvalue값만 
answer[answer['pvalue']<0.05]['pvalue']

1    5.041733e-27
2    5.962588e-04
3    7.010113e-04
4    1.125464e-14
Name: pvalue, dtype: float64

In [191]:
# 데이터프레임 중에서 pvalue값 중에서 가장 큰 pvalue = Drug에 가장 영향력있음
answer[answer['pvalue']<0.05]['pvalue'].max()

0.0007010113024729462

In [192]:
# 데이터프레임 중에서 pvalue값 중에서 가장 큰 인덱스번호 = Drug에 가장 영향력있음
answer[answer['pvalue']<0.05]['pvalue'].idxmax()

3

In [197]:
for_drug = answer[answer['pvalue'] < 0.05]
for_drug_best = for_drug.loc[for_drug['pvalue'].idxmax()]
for_drug_best

features      Age_gr
pvalue      0.000701
Name: 3, dtype: object

In [198]:
for_drug_best.name

3

In [202]:
for_drug_best.features

'Age_gr'

In [201]:
for_drug_best.pvalue

0.0007010113024729462

# 처방된 약에 영향력이 제일 큰 환자의 상태변수


In [206]:
print(f'Drug타입에 영향력을 많이 미치는 변수는 {for_drug_best.features}이고, p-value값은 {for_drug_best.pvalue:.5f}입니다.')

Drug타입에 영향력을 많이 미치는 변수는 Age_gr이고, p-value값은 0.00070입니다.


# 변수변환(범주->수치)

# 의사결정나무

# 코드 정리